//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Root {
    
    private RootFIELD_DATA[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FIELD_DATA", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RootFIELD_DATA[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootFIELD_DATA {
    
    private RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATION[] pROCESSING_DATA_SECTIONField;
    
    private string mSG_IDField;
    
    private string mSG_DTField;
    
    private string cISNUMField;
    
    private string mODCODField;
    
    private string sEQNUMField;
    
    private string lB__IDField;
    
    private string lINCODField;
    
    private string pRGNUMField;
    
    private string lINDESField;
    
    private string sUBGROUP_DESCRIPTIONField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TRACED_OPERATION", typeof(RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATION), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATION[] PROCESSING_DATA_SECTION {
        get {
            return this.pROCESSING_DATA_SECTIONField;
        }
        set {
            this.pROCESSING_DATA_SECTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MSG_ID {
        get {
            return this.mSG_IDField;
        }
        set {
            this.mSG_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MSG_DT {
        get {
            return this.mSG_DTField;
        }
        set {
            this.mSG_DTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CISNUM {
        get {
            return this.cISNUMField;
        }
        set {
            this.cISNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MODCOD {
        get {
            return this.mODCODField;
        }
        set {
            this.mODCODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SEQNUM {
        get {
            return this.sEQNUMField;
        }
        set {
            this.sEQNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LB__ID {
        get {
            return this.lB__IDField;
        }
        set {
            this.lB__IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LINCOD {
        get {
            return this.lINCODField;
        }
        set {
            this.lINCODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PRGNUM {
        get {
            return this.pRGNUMField;
        }
        set {
            this.pRGNUMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LINDES {
        get {
            return this.lINDESField;
        }
        set {
            this.lINDESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SUBGROUP_DESCRIPTION {
        get {
            return this.sUBGROUP_DESCRIPTIONField;
        }
        set {
            this.sUBGROUP_DESCRIPTIONField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATION {
    
    private RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEM[] sINGLE_ITEMField;
    
    private string oPCODEField;
    
    private string oPTYPEField;
    
    private string oPCYCLEField;
    
    private string oPTOOL_IDField;
    
    private string oP_RESULTField;
    
    private string oPERATORField;
    
    private string oPDATEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SINGLE_ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEM[] SINGLE_ITEM {
        get {
            return this.sINGLE_ITEMField;
        }
        set {
            this.sINGLE_ITEMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPCODE {
        get {
            return this.oPCODEField;
        }
        set {
            this.oPCODEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPTYPE {
        get {
            return this.oPTYPEField;
        }
        set {
            this.oPTYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPCYCLE {
        get {
            return this.oPCYCLEField;
        }
        set {
            this.oPCYCLEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPTOOL_ID {
        get {
            return this.oPTOOL_IDField;
        }
        set {
            this.oPTOOL_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OP_RESULT {
        get {
            return this.oP_RESULTField;
        }
        set {
            this.oP_RESULTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPERATOR {
        get {
            return this.oPERATORField;
        }
        set {
            this.oPERATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPDATE {
        get {
            return this.oPDATEField;
        }
        set {
            this.oPDATEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEM {
    
    private RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEMSINGLE_OP_RESULT[] sINGLE_OP_RESULTField;
    
    private string iTEM_IDField;
    
    private string iTEM_DESCField;
    
    private string iTEM_RESULTField;
    
    private string oPERATORField;
    
    private string oPTOOL_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SINGLE_OP_RESULT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEMSINGLE_OP_RESULT[] SINGLE_OP_RESULT {
        get {
            return this.sINGLE_OP_RESULTField;
        }
        set {
            this.sINGLE_OP_RESULTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ITEM_ID {
        get {
            return this.iTEM_IDField;
        }
        set {
            this.iTEM_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ITEM_DESC {
        get {
            return this.iTEM_DESCField;
        }
        set {
            this.iTEM_DESCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ITEM_RESULT {
        get {
            return this.iTEM_RESULTField;
        }
        set {
            this.iTEM_RESULTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPERATOR {
        get {
            return this.oPERATORField;
        }
        set {
            this.oPERATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPTOOL_ID {
        get {
            return this.oPTOOL_IDField;
        }
        set {
            this.oPTOOL_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEMSINGLE_OP_RESULT {
    
    private RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEMSINGLE_OP_RESULTMEASUREMENT[] mEASUREMENTField;
    
    private string tRY_IDField;
    
    private string tRY_RESULTField;
    
    private string oPERATORField;
    
    private string oPTOOL_IDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MEASUREMENT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEMSINGLE_OP_RESULTMEASUREMENT[] MEASUREMENT {
        get {
            return this.mEASUREMENTField;
        }
        set {
            this.mEASUREMENTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TRY_ID {
        get {
            return this.tRY_IDField;
        }
        set {
            this.tRY_IDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TRY_RESULT {
        get {
            return this.tRY_RESULTField;
        }
        set {
            this.tRY_RESULTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPERATOR {
        get {
            return this.oPERATORField;
        }
        set {
            this.oPERATORField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string OPTOOL_ID {
        get {
            return this.oPTOOL_IDField;
        }
        set {
            this.oPTOOL_IDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RootFIELD_DATAPROCESSING_DATA_SECTIONTRACED_OPERATIONSINGLE_ITEMSINGLE_OP_RESULTMEASUREMENT {
    
    private string mEAS_DESCRField;
    
    private string mEASUREField;
    
    private string vALUEField;
    
    private string umField;
    
    private string uPPER_TOLERANCEField;
    
    private string lOWER_TOLERANCEField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MEAS_DESCR {
        get {
            return this.mEAS_DESCRField;
        }
        set {
            this.mEAS_DESCRField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MEASURE {
        get {
            return this.mEASUREField;
        }
        set {
            this.mEASUREField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VALUE {
        get {
            return this.vALUEField;
        }
        set {
            this.vALUEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UM {
        get {
            return this.umField;
        }
        set {
            this.umField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string UPPER_TOLERANCE {
        get {
            return this.uPPER_TOLERANCEField;
        }
        set {
            this.uPPER_TOLERANCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LOWER_TOLERANCE {
        get {
            return this.lOWER_TOLERANCEField;
        }
        set {
            this.lOWER_TOLERANCEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
